name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            platform: linux-amd64
          - goos: linux
            goarch: arm64
            platform: linux-arm64
          - goos: darwin
            goarch: amd64
            platform: darwin-amd64
          - goos: darwin
            goarch: arm64
            platform: darwin-arm64
          - goos: windows
            goarch: amd64
            platform: windows-amd64
            extension: .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          binary_name="scriptify${{ matrix.extension }}"
          go build -ldflags="-s -w" -o "${binary_name}"

          # Create archive
          if [ "${{ matrix.goos }}" = "windows" ]; then
            archive_name="scriptify-${{ matrix.platform }}.zip"
            zip "${archive_name}" "${binary_name}"
          else
            archive_name="scriptify-${{ matrix.platform }}.tar.gz"
            tar -czf "${archive_name}" "${binary_name}"
          fi

          echo "ARCHIVE_NAME=${archive_name}" >> $GITHUB_ENV

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ARCHIVE_NAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}